server:
  port: ${PORT:8080}

spring:
  application:
    name: telegabot

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/db.changelog-master.yml


logging:
  level:
    org.dharbar.telegabot.client: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

api:
  rate:
    url: https://bank.gov.ua/NBUStatService/v1/statdirectory

  mono:
    url: https://api.monobank.ua
    token: ${API_MONO_TOKEN}

  notion:
    url: https://api.notion.com/v1
    token: ${API_NOTION_TOKEN}


  binancep2p:
    url: https://p2p.binance.com

  binance:
    url: https://api2.binance.com
    key: ${API_BINANCE_KEY}
    secret: ${API_BINANCE_SECRET}


telegram:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_TOKEN}
  my:
    chat-id: ${TELEGRAM_MY_CHAT_ID}

task:
  rates: 0 0 7,10 * * ?


# TODO
#spring.quartz.job-store-type=jdbc
#spring.quartz.jdbc.initialize-schema=always
