server:
  port: ${PORT:8080}

spring:
  application:
    name: telegabot


  datasource:
    hikari:
      auto-commit: false
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate

  liquibase:
    change-log: db/changelog/db.changelog-master.yml

  jpa:
    open-in-view: false

logging:
  level:
    org.dharbar.telegabot.client: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

api:
  rate:
    url: https://bank.gov.ua/NBUStatService/v1/statdirectory

  mono:
    url: https://api.monobank.ua
    token: ${API_MONO_TOKEN}

  notion:
    url: https://api.notion.com/v1
    token: ${API_NOTION_TOKEN}


  binancep2p:
    url: https://p2p.binance.com

  binance:
    url: https://api2.binance.com
    key: ${API_BINANCE_KEY}
    secret: ${API_BINANCE_SECRET}

  tiingo:
    url: https://api.tiingo.com/tiingo
    token: ${API_TIINGO_TOKEN}


telegram:
  name: ${TELEGRAM_BOT_NAME}
  token: ${TELEGRAM_TOKEN}
  my:
    chat-id: ${TELEGRAM_MY_CHAT_ID}

task:
  current-rate-message: 0 0 7,10 * * ?
  eod-ticker-price-update: 0 7 0 * * 1-5
  current-ticker-price-update: 0 0/5 * * * ?

vaadin:
  frontend:
    hotdeploy: false
