spring:
  application:
    name: telegabot

  datasource:
    url: jdbc:postgresql://localhost:5432/telegaBotDb

  jpa:
    show-sql: true


task:
  current-rate-message: 0 0 0 * 12 ?
  eod-ticker-price-update: 0 0 0 * 12 ?
  current-ticker-price-update: 0 0 0 */1 12 ?
